<a href="https://colab.research.google.com/github/johanajaramillom1-design/Repositorio_Entregable_2/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 1. Numpy

import numpy as np

# 1. Crear un arreglo

# 1.1 desde lista

arr = np.array([1,2,3,4])
print("Arreglo desde listas:")
print(arr)
print("\n")

# 1.2 desde matrices

mat = np.array([[1,2,3],[4,5,6]])
print("Matriz:")
print(mat)
print("\n")

# 1.3 con rangos

range = np.arange(0,10,2)
print("Arreglo con rangos:")
print(range)
print("\n")

# 1.4 arreglo con ceros y unos

zeros = np.zeros((3,3))
ones = np.ones((2,4))
print("Arreglo de ceros:")
print(zeros)
print("\n")
print("Arreglo de unos:")
print(ones)
print("\n")

# 1.5 aleatorios

random = np.random.rand(3,3)
random_int = np.random.randint(1,100,(3,3))
print("Arreglo aleatorio:")
print(random)
print("\n")
print("Arreglo aleatorio de enteros:")
print(random_int)

print("Arreglo desde listas:")

Arreglo desde listas:
[1 2 3 4]


Matriz:
[[1 2 3]
 [4 5 6]]


Arreglo con rangos:
[0 2 4 6 8]


Arreglo de ceros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Arreglo de unos:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Arreglo aleatorio:
[[0.91890551 0.24359887 0.02307572]
 [0.21934668 0.8146929  0.77717868]
 [0.14346343 0.70223227 0.86248477]]


Arreglo aleatorio de enteros:
[[ 3 45 92]
 [37 54 88]
 [64 16 66]]
Arreglo desde listas:


In [ ]:
# 2. Propiedades de un arreglo

# 2.1 numero de dimensiones

ndim = arr.ndim
print("Numero de dimensiones:")
print(ndim)
print("\n")

# 2.2 forma

shape = arr.shape
print("Forma:")
print(shape)
print("\n")

# 2.3 numero de elementos

size = arr.size
print("Numero de elementos:")
print(size)
print("\n")

# 2.4 tipo de dato

dtype = arr.dtype
print("Tipo de dato:")
print(dtype)
print("\n")

Numero de dimensiones:
1


Forma:
(4,)


Numero de elementos:
4


Tipo de dato:
int64




In [ ]:
# 3 Indexación y slicing

# arreglo

arr2 = np.array([10,20,30,40,50])
index = arr2[0]
index_range = arr2[1:4]
slicing = arr2[::-1]

print("indice: ")
print(index)
print("\n")
print("indice con rango: ")
print(index_range)
print("\n")
print("slicing: ")
print(slicing)
print("\n")

# matrices

mat2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
index_mat = mat2[1,2]
index_colum = mat2[:,0]
index_row = mat2[1,:]
submatriz = mat2[0:2,1:3]

print("matriz: ")
print(mat2)
print("indice: ")
print(index_mat)
print("\n")
print("indice de columna: ")
print(index_colum)
print("\n")
print("indice de fila: ")
print(index_row)
print("subamatriz: ")
print(submatriz)
print("\n")

indice: 
10


indice con rango: 
[20 30 40]


slicing: 
[50 40 30 20 10]


matriz: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
indice: 
6


indice de columna: 
[1 4 7]


indice de fila: 
[4 5 6]
subamatriz: 
[[2 3]
 [5 6]]




In [ ]:
# 4. operaciones matematicas

sum = arr + 5
print("suma: ")
print(sum)

mult = arr * 2
print("multiplicacion: ")
print(mult)

div = arr / 3
print("division: ")
print(div)

sub = arr ** 2
print("exponente: ")
print(sub)

# entre arreglos

a= np.array([1,2,3])
b= np.array([4,5,6])

suma_arr = a + b
mult_arr = a * b
div_arr = a / b
exp_arr = a ** b

print("suma de arreglos: ")
print(suma_arr)
print("multiplicacion de arreglos: ")
print(mult_arr)
print("division de arreglos: ")
print(div_arr)
print("exponente de arreglos: ")
print(exp_arr)

suma: 
[6 7 8 9]
multiplicacion: 
[2 4 6 8]
division: 
[0.33333333 0.66666667 1.         1.33333333]
exponente: 
[ 1  4  9 16]
suma de arreglos: 
[5 7 9]
multiplicacion de arreglos: 
[ 4 10 18]
division de arreglos: 
[0.25 0.4  0.5 ]
exponente de arreglos: 
[  1  32 729]


In [ ]:
# 5. Funciones

sqrt = np.sqrt(arr)
print("Raiz cuadrada: ")
print(sqrt)

mean = np.mean(arr)
print("Media: ")
print(mean)

sumx = np.sum(arr)
print("Suma: ")
print(sumx)

max = np.max(arr)
print("Maximo: ")
print(max)

min = np.min(arr)
print("Minimo: ")
print(min)

std = np.std(arr)
print("Desviacion estandar: ")
print(std)

Raiz cuadrada: 
[1.         1.41421356 1.73205081 2.        ]
Media: 
2.5
Suma: 
10
Maximo: 
4
Minimo: 
1
Desviacion estandar: 
1.118033988749895


In [ ]:
# 6. Ejercicio de la pareja tomamos como ejemplo el Numpy

import numpy as np

# 1. Crear un arreglo

# 1.1 desde lista
arr = np.array([5, 10, 15, 20])
print("Arreglo desde lista:")
print(arr)
print("\n")

# 1.2 desde matrices
mat = np.array([[7, 8, 9], [10, 11, 12]])
print("Matriz 2x3:")
print(mat)
print("\n")

# 1.3 con rangos
range_arr = np.arange(5, 21, 5)  # Empieza en 5 hasta 20, saltos de 5
print("Arreglo con rangos:")
print(range_arr)
print("\n")

# 1.4 arreglo con ceros y unos
zeros = np.zeros((2,5))  # 2 filas, 5 columnas
ones = np.ones((4,2))    # 4 filas, 2 columnas
print("Arreglo de ceros 2x5:")
print(zeros)
print("\n")
print("Arreglo de unos 4x2:")
print(ones)
print("\n")

# 1.5 aleatorios
random_float = np.random.rand(2,4)  # números entre 0 y 1
random_int = np.random.randint(50, 101, (3,3))  # enteros entre 50 y 100
print("Arreglo aleatorio de floats 2x4:")
print(random_float)
print("\n")
print("Arreglo aleatorio de enteros 3x3 entre 50 y 100:")
print(random_int)

Arreglo desde lista:
[ 5 10 15 20]


Matriz 2x3:
[[ 7  8  9]
 [10 11 12]]


Arreglo con rangos:
[ 5 10 15 20]


Arreglo de ceros 2x5:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Arreglo de unos 4x2:
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


Arreglo aleatorio de floats 2x4:
[[0.96670723 0.20548985 0.4563215  0.06163079]
 [0.54946621 0.91404502 0.2608276  0.91335102]]


Arreglo aleatorio de enteros 3x3 entre 50 y 100:
[[ 90  94  59]
 [ 58  85  91]
 [ 51  60 100]]
